Repository samridhiagarwal/hactoberfest-2021-C-directory, pull requests merged in 2021-11, with the labels that each got.

#41 polymorphism.cpp
  polymorphism.cpp
Labels: good first issue, hacktoberfest-accepted

#42 Create selection sort_sart.cpp
  selection sort_sart.cpp
Labels: good first issue

#43 Added binary.c
  binary.c
Labels: hacktoberfest-accepted
